language: php

php:
  - 7.0

env:
  - SYMFONY_VERSION="2.*" GUZZLE_VERSION="3.*"

before_script:
  - composer self-update
  - composer --version
  - composer require symfony/http-foundation:${SYMFONY_VERSION} --no-update
  - composer require guzzle/http:${GUZZLE_VERSION} --no-update
  - composer install -n --dev --prefer-source

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpunit --coverage-text
